w = load('HarmonicLogCR_n0.csv')
xR = w(:, 2)
R0 = w(:, 3)
w = load('HarmonicLogCR_n9.csv')
xRn = w(:, 2)
Rn = w(:, 3)
w = load('HarmonicLogCR_n0_deriv.csv')
xDR = w(:, 2)
DR0 = w(:, 3)
w = load('HarmonicLogCR_n9_deriv.csv')
xDRn = w(:, 2)
DRn = w(:, 3)

w = load('LaguerreLogCR_n0.csv')
xC = w(:, 2)
C0 = w(:, 3)
w = load('LaguerreLogCR_n9.csv')
xCn = w(:, 2)
Cn = w(:, 3)
w = load('LaguerreLogCR_n0_deriv.csv')
xDC = w(:, 2)
DC0 = w(:, 3)
w = load('LaguerreLogCR_n9_deriv.csv')
xDCn = w(:, 2)
DCn = w(:, 3)
%
%
subplot(2,2,1)
plot (xR, R0, 'k-')
hold
plot (xRn, Rn, 'k--')
set(gca, 'XLim', [-4, 4])
% set(gca, 'YLim', [-5, 10])
ylabel('Laguerre basis')
xlabel('\it\rho')
legend('\itP_0(\rho)', '\itP_1_9(\rho)')
title('A.')
%
subplot(2,2,2)
plot (xC, C0, 'k-')
hold
plot (xCn, Cn, 'k--')
set(gca, 'XLim', [-4, 4])
% set(gca, 'YLim', [-5, 10])
xlabel('\itx')
legend('\itF_0(x)', '\itF_1_9(x)')
title('B.')
%
subplot(2,2,3)
plot (xDR, DR0, 'k-')
hold
plot (xDRn, DRn, 'k--')
set(gca, 'XLim', [-4, 4])
% set(gca, 'YLim', [-20, 40])
ylabel('First derivative')
xlabel('\it\rho')
legend('\itP''_0(\rho)', '\itP''_1_9(\rho)')
title('C.')
%
subplot(2,2,4)
plot (xDC, DC0, 'k-')
hold
plot (xDCn, DCn, 'k--')
set(gca, 'XLim', [-4, 4])
% set(gca, 'YLim', [-20, 40])
xlabel('\itx')
legend('\itF''_0(x)', '\itF''_1_9(x)')
title('D.')

