w = load('HeA_1_1S.csv')
x_1 = w(:, 2)
A_1 = w(:, 3)
w = load('HeB_1_1S.csv')
B_1 = w(:, 3)
w = load('HeC_1_1S.csv')
C_1 = w(:, 3)

w = load('HeA_2_1S.csv')
x_2 = w(:, 2)
A_2 = w(:, 3)
w = load('HeB_2_1S.csv')
B_2 = w(:, 3)
w = load('HeC_2_1S.csv')
C_2 = w(:, 3)

w = load('HyA_1_1S.csv')
xHy_1 = w(:, 2)
HyA_1 = w(:, 3)
w = load('HyB_1_1S.csv')
HyB_1 = w(:, 3)
w = load('HyC_1_1S.csv')
HyC_1 = w(:, 3)

% w = load('HyA_2_1S_L0.csv')
w = load('HyA_2_1S.csv')
xHy_2 = w(:, 2)
HyA_2 = w(:, 3)
% w = load('HyB_2_1S_L0.csv')
w = load('HyB_2_1S.csv')
HyB_2 = w(:, 3)
% w = load('HyC_2_1S_L0.csv')
w = load('HyC_2_1S.csv')
HyC_2 = w(:, 3)
%
subplot(2,2,1)
plot (x_2, A_2, 'k-')
hold
plot (x_2, B_2, 'k--')
plot (x_2, C_2, 'k:')
ylabel('log_1_0(Energy - Exact)')
legend('\it\lambda=4', '\it\lambda=2', '\it\lambda=1')
title('A. He 2^1S')
set(gca, 'XLim', [0, 55])
set(gca, 'YLim', [-5, 0])
%
subplot(2,2,2)
plot (xHy_2, HyA_2, 'k-')
hold
plot (xHy_2, HyB_2, 'k--')
plot (xHy_2, HyC_2, 'k:')
% ylabel('log_1_0(Energy - Exact)')
legend('\it\lambda=2', '\it\lambda=1', '\it\lambda=0.5')
title('B. H^- 2^1S (continuum) ')
set(gca, 'XLim', [0, 50])
set(gca, 'YLim', [-5, 0])
%
subplot(2,2,3)
plot (x_1, A_1, 'k-')
hold
plot (x_1, B_1, 'k--')
plot (x_1, C_1, 'k:')
ylabel('log_1_0(Energy - Exact)')
xlabel('cumilative maximum N')
legend('\it\lambda=4', '\it\lambda=2', '\it\lambda=1')
title('C. He 1^1S ')
set(gca, 'XLim', [0, 55])
set(gca, 'YLim', [-5, 0])
%
subplot(2,2,4)
plot (xHy_1, HyA_1, 'k-')
hold
plot (xHy_1, HyB_1, 'k--')
plot (xHy_1, HyC_1, 'k:')
% ylabel('log_1_0(Energy - Exact)')
xlabel('cumilative maximum N')
% legend('\it\alpha(L)=2L+2, \lambda=2*2', '\it\alpha(L)=2L+2, \lambda=2*1.6875', '\it\alpha(L)=2, \lambda=2')
legend('\it\lambda=2', '\it\lambda=1', '\it\lambda=0.5')
title('D. H^- 1^1S')
set(gca, 'XLim', [0, 55])
set(gca, 'YLim', [-5, 0])
%
