w = load('bspline_basis_k3_i0.csv')
xA_1 = w(:, 2)
A_1 = w(:, 3)
w = load('bspline_basis_k3_i1.csv')
xA_2 = w(:, 2)
A_2 = w(:, 3)
w = load('bspline_basis_k3_i2.csv')
xA_3 = w(:, 2)
A_3 = w(:, 3)
w = load('bspline_basis_k3_i3.csv')
xA_4 = w(:, 2)
A_4 = w(:, 3)
w = load('bspline_basis_k3_i4.csv')
xA_5 = w(:, 2)
A_5 = w(:, 3)

w = load('bspline_orthog_k3_i0.csv')
xB_1 = w(:, 2)
B_1 = w(:, 3)
w = load('bspline_orthog_k3_i1.csv')
xB_2 = w(:, 2)
B_2 = w(:, 3)
w = load('bspline_orthog_k3_i2.csv')
xB_3 = w(:, 2)
B_3 = w(:, 3)
w = load('bspline_orthog_k3_i3.csv')
xB_4 = w(:, 2)
B_4 = w(:, 3)
w = load('bspline_orthog_k3_i4.csv')
xB_5 = w(:, 2)
B_5 = w(:, 3)

w = load('bspline_orthog_k5_i0.csv')
xD_1 = w(:, 2)
D_1 = w(:, 3)
w = load('bspline_orthog_k5_i1.csv')
xD_2 = w(:, 2)
D_2 = w(:, 3)
w = load('bspline_orthog_k5_i2.csv')
xD_3 = w(:, 2)
D_3 = w(:, 3)
w = load('bspline_orthog_k5_i3.csv')
xD_4 = w(:, 2)
D_4 = w(:, 3)
w = load('bspline_orthog_k5_i4.csv')
xD_5 = w(:, 2)
D_5 = w(:, 3)
%
subplot(2,2,1)
plot (xA_1, A_1, 'k-')
hold
plot (xA_2, A_2, 'k--')
plot (xA_3, A_3, 'k:')
plot (xA_4, A_4, 'k-.')
plot (xA_5, A_5, 'k-')
% set(gca, 'XLim', [0, 4])
set(gca, 'YLim', [0, 1.2])
title('A.')
%
subplot(2,2,3)
plot (xB_1, B_1, 'k-')
hold
plot (xB_2, B_2, 'k--')
plot (xB_3, B_3, 'k:')
plot (xB_4, B_4, 'k-.')
plot (xB_5, B_5, 'k-')
% set(gca, 'XLim', [0, 4])
% plot (xB_5, B_5, 'k-')
% set(gca, 'YLim', [0, 1.2])
title('B.')
% %
%
subplot(2,2,4)
plot (xD_1, D_1, 'k-')
hold
plot (xD_2, D_2, 'k--')
plot (xD_3, D_3, 'k:')
plot (xD_4, D_4, 'k-.')
plot (xD_5, D_5, 'k-')
% set(gca, 'XLim', [0, 4])
% plot (xB_5, B_5, 'k-')
% set(gca, 'YLim', [0, 1.2])
title('D.')
