/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kingroup_0005fv2_partition_graph_GraphAlgJNI */

#ifndef _Included_kingroup_0005fv2_partition_graph_GraphAlgJNI
#define _Included_kingroup_0005fv2_partition_graph_GraphAlgJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kingroup_0005fv2_partition_graph_GraphAlgJNI
 * Method:    partitionTestHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kingroup_1v2_partition_graph_GraphAlgJNI_partitionTestHelloWorld
  (JNIEnv *, jobject);

/*
 * Class:     kingroup_0005fv2_partition_graph_GraphAlgJNI
 * Method:    partitionTestIntArray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_kingroup_1v2_partition_graph_GraphAlgJNI_partitionTestIntArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     kingroup_0005fv2_partition_graph_GraphAlgJNI
 * Method:    partition
 * Signature: ([[I)V
 */
JNIEXPORT void JNICALL Java_kingroup_1v2_partition_graph_GraphAlgJNI_partition
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
