/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ledax_LedaWeightAssignmentJNI */

#ifndef _Included_org_ledax_LedaWeightAssignmentJNI
#define _Included_org_ledax_LedaWeightAssignmentJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ledax_LedaWeightAssignmentJNI
 * Method:    calc
 * Signature: ([[IZ)I
 */
JNIEXPORT jint JNICALL Java_org_ledax_LedaWeightAssignmentJNI_calc
  (JNIEnv *, jobject, jobjectArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
